feh --bg-fill --randomize ~/Wallpapers/
setxkbmap gb -option compose:menu
xset r rate 200 100
xmodmap ~/.Xmodmap
xrdb ~/.Xresources
compton --config=/home/chris/Dotfiles/compton/compton.conf &
xset -dpms s off
exec xmonad
