feh --bg-fill --randomize ~/Wallpapers/
setxkbmap gb -option compose:menu
xset r rate 200 100
xmodmap ~/.Xmodmap
xrdb ~/.Xresources
xset -dpms s off
emacs --daemon &
pulseaudio --start &
mpd &
~/.screenlayout/rots.sh
exec xmonad
