feh --bg-fill ~/Wallpapers/1483932766360.jpg
setxkbmap gb -option compose:menu
xset r rate 200 100
xmodmap ~/.Xmodmap
xrdb ~/.Xresources
compton --config=/home/chris/Dotfiles/compton/compton.conf &
xset -dpms s off
emacs --daemon
urxvtd &
exec xmonad
